sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectOverviewView.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/projectoverview/Project.groovy

This PR adds the progress bar into the grid

Add progress bar to grid

---

sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/DependencyManager.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/StatusOverviewApp.groovy

This PR adds the dependency manager class

Add dependency manager

---

.github/workflows/changelog-update.yml
CHANGELOG.rst
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/StatusOverviewApp.groovy

Adds the GH worfkflow that checks for Changelog updates.

Add Github workflow

---

sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/CountSamplesPresenter.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/count/CountSamples.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/count/CountSamplesInput.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/count/CountSamplesOutput.groovy
sample-tracking-status-overview-domain/src/test/groovy/life/qbic/business/samples/count/CountSamplesSpec.groovy

Implement the use case logic for counting the failed qc samples

Count failed qc samples

---

sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/CountSamplesPresenter.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/count/CountSamples.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/count/CountSamplesInput.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/count/CountSamplesOutput.groovy

extends the use case in the domain layer

Add available data samples to CountSamples use case

---

sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/datasources/samples/SamplesDbConnector.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/datasources/subscriptions/SubscriptionsDbConnector.groovy

Implementation of the datasource to subscribe a subscriber to a project

add implementation for subscription data source

---

sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/project/subscribe/SubscribeProject.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/project/subscribe/SubscribeProjectInput.groovy
sample-tracking-status-overview-domain/src/test/groovy/life/qbic/business/project/subscribe/SubscribeProjectSpec.groovy

Update interface methods

---

sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectOverviewView.groovy

removes the manual sorting option of the project table columns

remove manual sorting option

---

sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/DependencyManager.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/LoadProjectsPresenter.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectOverviewViewModel.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectSummary.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/datasources/OpenBisConnector.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/resource/project/ProjectResourceService.groovy
sample-tracking-status-overview-app/src/test/groovy/life/qbic/portal/sampletracking/resource/project/ProjectResourceServiceSpec.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/project/Project.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/project/load/LoadProjectsDataSource.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/project/load/LoadProjectsOutput.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/count/CountSamples.groovy
sample-tracking-status-overview-domain/src/test/groovy/life/qbic/business/project/load/LoadProjectsSpec.groovy

This provides you with the Project DTO

Introduce project dto

---

sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/DependencyManager.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/LoadProjectsPresenter.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectOverviewViewModel.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectSummary.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/datasources/OpenBisConnector.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/resource/project/ProjectResourceService.groovy
sample-tracking-status-overview-app/src/test/groovy/life/qbic/portal/sampletracking/resource/project/ProjectResourceServiceSpec.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/project/Project.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/project/load/LoadProjectsDataSource.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/project/load/LoadProjectsOutput.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/count/CountSamples.groovy
sample-tracking-status-overview-domain/src/test/groovy/life/qbic/business/project/load/LoadProjectsSpec.groovy

Many thanks for contributing to this project!
**PR Checklist**
Please fill in the appropriate checklist below (delete whatever is not relevant). These are the most common things requested on pull requests (PRs).
**Description of changes**
Please state what you've changed and how it might affect the user.
**Technical details**
Please state any technical details such as limitations, reasons for additional dependencies, benchmarks etc. here.
**Additional context**
Add any other context or screenshots here.

Feature - subscription information

---

CHANGELOG.rst
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectOverviewView.groovy

Refactoring of the layout:
- makes the title larger
- adds a small spacer between actual content and title
The intention of these changes are to add more whitespace and create a better UX by helping the user to spot the important features more easily.

Minor layout refactoring

---

sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/AppView.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/Resettable.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectOverviewView.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/sampleoverview/SampleOverviewView.groovy
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/sampleoverview/samplelist/ProjectSamplesView.groovy
sample-tracking-status-overview-domain/src/main/groovy/life/qbic/business/samples/info/GetSamplesInfo.groovy

Adds listener to the projectSelected property of the ProjectOverviewViewmodel
[dm-101](https://qbicsoftware.atlassian.net/jira/software/c/projects/DM/boards/4?modal=detail&selectedIssue=DM-101)

Add listener on selected project change

---

sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectOverviewView.groovy
sample-tracking-status-overview-app/src/main/webapp/VAADIN/themes/mytheme/mytheme.scss

**Description of changes**
Addresses DM-82.
Introduces a Stylegenerator to the projectgrid and custom css to make cursor into pointer form when hovering over projectgrid

DM-82/clickable-project-row

---

CHANGELOG.rst
pom.xml
sample-tracking-status-overview-app/pom.xml
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/datasources/subscriptions/SubscriptionsDbConnector.groovy
sample-tracking-status-overview-domain/pom.xml

1.0.0-beta.10 (2022-01-18)
---------------------------
**Added**
**Fixed**
* Use user id instead of email field to find subscriber in the database (#192)
**Dependencies**
**Deprecated**

Hotfix 1.0.0. beta.10

---

sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/sampleoverview/SampleView.groovy

Adds the current sample coloring to the new UI

Add sample coloring back

---

CHANGELOG.rst
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy
sample-tracking-status-overview-app/src/main/webapp/VAADIN/themes/mytheme/mytheme.scss

Adds the tooltips to the new UI

Add tooltips to download button and table headers

---

sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy

Refresh the grid after subscriptions

Refresh grid after subscription

---

sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/MainPage.groovy

Remove the margin to avoid too much white space and give the grid more room

Remove margin 

---

CHANGELOG.rst
pom.xml
sample-tracking-status-overview-app/pom.xml
sample-tracking-status-overview-domain/pom.xml

Release 1.0.0

---

CHANGELOG.rst
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy

Refreshes the data provider correctly.

DM-215 Subscribing to projects creates deadlock in filter

---

CHANGELOG.rst
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy

Fix typo and use more intuitive wording for filtering

Improve UX

---

CHANGELOG.rst
pom.xml
sample-tracking-status-overview-app/pom.xml
sample-tracking-status-overview-app/src/main/groovy/life/qbic/portal/sampletracking/components/projectoverview/ProjectView.groovy
sample-tracking-status-overview-domain/pom.xml

1.0.1 (2022-02-01)
---------------------------
**Added**
**Fixed**
* Fix wording in sorting to improve UX (#213)
* Search field not working after subscription change (#212)
**Dependencies**
**Deprecated**

Release 1.0.1
